services:
  program:
    container_name: program-microservice
    build:
      context: .
      dockerfile: apps\training-program\Dockerfile
    ports:
      - '4001:4001'
    depends_on:
      - postgres
    environment:
      - .env

  postgres:
    image: postgres:latest
    container_name: coach-app-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
